version: "3"

services:
  gs:
    build: .
    tty: true
    privileged: true
    network_mode: "host"
    ipc: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./colcon_ws:/root/colcon_ws 
    environment:
      - DISPLAY=$DISPLAY
