version: "3"

services:
  gs:
    build: .
    tty: true
    privileged: true
    network_mode: "host"
    ipc: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./colcon_ws:/root/colcon_ws 
        # - ./super_client_configuration_file.xml:/root/super_client_configuration_file.xml
    environment:
      - DISPLAY=$DISPLAY
        # - FASTRTPS_DEFAULT_PROFILES_FILE=/root/super_client_configuration_file.xml
      # - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # - ROS_DISCOVERY_SERVER=192.168.1.150:11811
      - ROS_DOMAIN_ID=2
